services:
  - type: web
    name: insurance-report-api
    env: python
    region: ohio  # Choose your region
    plan: starter  # Choose your plan
    buildCommand: |
      # Install LibreOffice for PDF conversion on Linux
      apt-get update && apt-get install -y libreoffice
      
      # Install Python dependencies
      pip install -r backend/requirements.txt
    startCommand: python -m uvicorn render_app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ENVIRONMENT
        value: production
    # Add your other environment variables from your Render dashboard
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: your-db-name
    #     property: connectionString
    scaling:
      minInstances: 1
      maxInstances: 1 