from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches


def create_default_template():
    """Create a default template for insurance reports"""
    doc = Document()

    # Set page margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Add title
    title = doc.add_heading("Insurance Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Add subtitle
    subtitle = doc.add_paragraph("Report generated by Insurance Report Generator")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.style = "Subtitle"

    # Add a few section headers (these will be replaced when the document is generated)
    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph("This section will contain a summary of the insurance report.")

    doc.add_heading("Claim Information", level=1)
    doc.add_paragraph("This section will contain details about the insurance claim.")

    doc.add_heading("Policy Details", level=1)
    doc.add_paragraph(
        "This section will contain information about the insurance policy."
    )

    doc.add_heading("Assessment", level=1)
    doc.add_paragraph("This section will contain the assessment of the claim.")

    doc.add_heading("Recommendations", level=1)
    doc.add_paragraph(
        "This section will contain recommendations based on the claim assessment."
    )

    # Save the document
    templates_dir = Path(__file__).parent
    doc.save(templates_dir / "default.docx")
    print(f"Default template created at {templates_dir / 'default.docx'}")


if __name__ == "__main__":
    create_default_template()
