import React, { useState } from 'react';
import {
  Box,
  Container,
  Typography,
  Alert,
  CircularProgress,
  Stepper,
  Step,
  StepLabel,
  Button,
  TextField,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
} from '@mui/material';
import DocumentUpload from '../components/DocumentUpload';
import AdditionalInfo from '../components/AdditionalInfo';
import { analyzeDocuments, generateReport, refineReport } from '../services/api';
import { AnalysisResponse, ReportPreview } from '../types';
// Define the interface matching the one in AdditionalInfo component
interface ComponentAnalysisDetails {
  valore: string;
  confidenza: 'ALTA' | 'MEDIA' | 'BASSA';
  richiede_verifica: boolean;
}
import { AnalysisDetails as GlobalAnalysisDetails } from '../types';

type StepType = 'upload' | 'additional-info' | 'preview';

// Local interfaces that map types between global and component-specific types
interface LocalAnalysisDetails {
  valore: string;
  confidenza: 'ALTA' | 'MEDIA' | 'BASSA';
  richiede_verifica: boolean;
  // Keep original properties for mapping back
  value: string;
  confidence: number;
  source: string;
}

interface LocalAnalysisResponse {
  extractedVariables: Record<string, string>;
  analysisDetails: Record<string, LocalAnalysisDetails>;
  fieldsNeedingAttention: string[];
}

// Helper function to map global types to component-specific types
const mapToComponentTypes = (details: Record<string, GlobalAnalysisDetails>): Record<string, ComponentAnalysisDetails> => {
  const result: Record<string, ComponentAnalysisDetails> = {};
  
  Object.entries(details).forEach(([key, detail]) => {
    result[key] = {
      valore: detail.value || 'Non fornito',
      confidenza: detail.confidence > 0.8 ? 'ALTA' : 
                 detail.confidence > 0.5 ? 'MEDIA' : 'BASSA',
      richiede_verifica: detail.confidence < 0.7
    };
  });
  
  return result;
};

const GenerateReport: React.FC = () => {
  const [currentStep, setCurrentStep] = useState<StepType>('upload');
  const [documentIds, setDocumentIds] = useState<string[]>([]);
  const [analysisResponse, setAnalysisResponse] = useState<LocalAnalysisResponse | null>(null);
  const [reportPreview, setReportPreview] = useState<ReportPreview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [showInstructionsDialog, setShowInstructionsDialog] = useState(false);
  const [instructions, setInstructions] = useState('');

  const handleDocumentsUploaded = async (ids: string[]) => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await analyzeDocuments(ids);
      // Convert the response to our local format
      const localResponse: LocalAnalysisResponse = {
        extractedVariables: response.extractedVariables,
        analysisDetails: {},
        fieldsNeedingAttention: response.fieldsNeedingAttention
      };
      
      // Map standard fields to local Italian field names
      Object.entries(response.analysisDetails).forEach(([key, details]) => {
        localResponse.analysisDetails[key] = {
          ...details,
          valore: details.value || 'Non fornito',
          confidenza: details.confidence > 0.8 ? 'ALTA' : 
                     details.confidence > 0.5 ? 'MEDIA' : 'BASSA',
          richiede_verifica: details.confidence < 0.7
        };
      });
      
      setAnalysisResponse(localResponse);
      setDocumentIds(ids);
      setCurrentStep('additional-info');
    } catch (err) {
      setError('Si è verificato un errore durante l\'analisi dei documenti. Riprova.');
      console.error('Error analyzing documents:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleAdditionalInfo = async (additionalInfo: string) => {
    setIsLoading(true);
    setError(null);
    try {
      const preview = await generateReport({
        documentIds,
        additionalInfo,
        reportId: '', // Empty string as this will be generated by the API
      });
      setReportPreview(preview as unknown as ReportPreview); // Type cast since the API response structure differs
      setCurrentStep('preview');
    } catch (err) {
      setError('Si è verificato un errore durante la generazione del report. Riprova.');
      console.error('Error generating report:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleRefineReport = async () => {
    if (!instructions.trim() || !reportPreview?.reportId) return;
    
    setIsLoading(true);
    setError(null);
    try {
      const preview = await refineReport(reportPreview.reportId, instructions);
      setReportPreview(preview);
      setShowInstructionsDialog(false);
      setInstructions('');
    } catch (err) {
      setError('Si è verificato un errore durante la modifica del report. Riprova.');
      console.error('Error refining report:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleBack = () => {
    if (currentStep === 'additional-info') {
      setCurrentStep('upload');
    } else if (currentStep === 'preview') {
      setCurrentStep('additional-info');
    }
  };

  const steps = [
    { label: 'Carica Documenti', completed: currentStep !== 'upload' },
    { label: 'Revisiona e Aggiungi Informazioni', completed: currentStep === 'preview' },
    { label: 'Anteprima Report', completed: false },
  ];

  const handleDownload = () => {
    if (reportPreview?.downloadUrl) {
      // Ensure we're using the DOCX endpoint
      let downloadUrl = reportPreview.downloadUrl;
      
      // Check if the URL already contains '/docx/'
      if (!downloadUrl.includes('/docx/')) {
        // Insert 'docx/' before the report ID in the URL
        const parts = downloadUrl.split('/');
        const lastPart = parts[parts.length - 1];
        downloadUrl = downloadUrl.replace(lastPart, `docx/${lastPart}`);
      }
      
      window.location.href = downloadUrl;
      
      // Show a notice that the report will be removed after download
      setTimeout(() => {
        alert('Nota: Tutti i file caricati sono stati eliminati dal server dopo il download.');
      }, 2000); // Show the alert 2 seconds after initiating download
    }
  };

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" gutterBottom>
          Generazione Report
        </Typography>
        <Stepper activeStep={steps.findIndex(s => !s.completed)} sx={{ mb: 4 }}>
          {steps.map((step, index) => (
            <Step key={index} completed={step.completed}>
              <StepLabel>{step.label}</StepLabel>
            </Step>
          ))}
        </Stepper>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {isLoading && (
        <Box sx={{ display: 'flex', justifyContent: 'center', my: 4 }}>
          <CircularProgress />
        </Box>
      )}

      {!isLoading && currentStep === 'upload' && (
        <DocumentUpload
          onUploadComplete={handleDocumentsUploaded}
          isLoading={isLoading}
        />
      )}

      {!isLoading && currentStep === 'additional-info' && analysisResponse && (
        <AdditionalInfo
          documentIds={documentIds}
          extractedVariables={analysisResponse.extractedVariables}
          analysisDetails={mapToComponentTypes(analysisResponse.analysisDetails)}
          fieldsNeedingAttention={analysisResponse.fieldsNeedingAttention}
          onSubmit={handleAdditionalInfo}
          onBack={handleBack}
        />
      )}

      {!isLoading && currentStep === 'preview' && reportPreview && (
        <Box>
          <Box sx={{ mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Typography variant="h5">
              Anteprima Report
            </Typography>
            <Box sx={{ display: 'flex', gap: 2 }}>
              <Button
                variant="outlined"
                onClick={() => setShowInstructionsDialog(true)}
              >
                Modifica Report
              </Button>
              <Button
                variant="contained"
                onClick={handleDownload}
              >
                Scarica DOCX
              </Button>
            </Box>
          </Box>

          <Box sx={{ width: '100%', height: '600px', border: '1px solid rgba(0, 0, 0, 0.12)', borderRadius: 1 }}>
            <iframe
              src={reportPreview.previewUrl}
              style={{ width: '100%', height: '100%', border: 'none' }}
              title="Report Preview"
            />
          </Box>
        </Box>
      )}

      <Dialog
        open={showInstructionsDialog}
        onClose={() => setShowInstructionsDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          Modifica Report
        </DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Inserisci le tue istruzioni per modificare il report. Sii specifico riguardo alle modifiche desiderate.
          </Typography>
          <TextField
            fullWidth
            multiline
            rows={6}
            label="Istruzioni per la Modifica"
            value={instructions}
            onChange={(e) => setInstructions(e.target.value)}
            placeholder="Es: Aggiungi più dettagli sulla dinamica dell'evento, riorganizza la sezione dei danni..."
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowInstructionsDialog(false)}>
            Annulla
          </Button>
          <Button
            onClick={handleRefineReport}
            variant="contained"
            disabled={!instructions.trim()}
          >
            Applica Modifiche
          </Button>
        </DialogActions>
      </Dialog>
    </Container>
  );
};

export default GenerateReport; 